inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - rubocop-rspec
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.5
  SuggestExtensions: false
  Exclude:
    - "db/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
