name: Build and Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruby-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
        gemfile:
          - 'gemfiles/Gemfile.pagy-5'
          - 'gemfiles/Gemfile.pagy-6'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up using Ruby ${{ matrix.ruby-version }} with Gemfile '${{ matrix.gemfile }}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          rubygems: latest
      - name: Run tests
        run: bundle exec rspec

  ruby-modern:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
        gemfile:
          - 'gemfiles/Gemfile.pagy-7'
          - 'gemfiles/Gemfile.pagy-8'
          - 'gemfiles/Gemfile.pagy-9'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up using Ruby ${{ matrix.ruby-version }} with Gemfile '${{ matrix.gemfile }}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          rubygems: latest
      - name: Run tests
        run: bundle exec rspec
